---
- name: Prepare Bird1
  hosts: router1
  user: vagrant
  become: yes
  gather_facts: no

  tasks:

  - name: Install BIRD PPA
    apt_repository: 
      repo: ppa:cz.nic-labs/bird

  - name: Install Bird
    apt: 
      name: bird 
      state: present 
      update_cache: yes

  - name: Install LLDP
    apt: 
      name: lldpd 
      state: present 
      update_cache: yes

  - name: Bird Configuration
    template: src={{inventory_hostname}}.conf dest=/etc/bird/bird.conf

  - name: Start Necessary Services
    service: name={{ item }} state=started
    with_items:
      - bird
      - lldpd

